# Generated by Django 3.1.1 on 2023-03-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20230316_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='conversation',
            new_name='chat',
        ),
    ]
