# Generated by Django 3.1.1 on 2023-03-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230313_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image_url',
            new_name='image',
        ),
    ]
